sudo: required
dist: trusty
language: python

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - sudo pip install pytest-cov wheel

script:
  - py.test --cov=csirtg_indicator --cov-fail-under=50
  - python setup.py sdist bdist bdist_wheel

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: ZbNOPb2+tOR3ECXqOncoFfoyHIl7BxiN/Paw3sbcKRkuWv5B7vUs/Mpfl1AedIWYlUznAG7Y/SfLncwOUNSac2lIDPbw33BtMYtGaDCqay5YkJXlCamS6Id1hMdj5gvDGJzUsaimeqAx6+Gz5i9gWi7AIqmXG6bvl1lOwG3ALOXWe7yDWveOM4d9fx5RYYsd0XTSuM6Sd5fA7NGu6ViUyMvs5foyW5g4L4OCBA/N4hCCi85HTuNk2+xjwmEa2CMo+mGZVt5J2mMJeTvng07xdkHeBKbLUNBcD4jhzOGXtqfcJJCpBWGFkn4V1fX8RFcIDcVfveX/cmcfIv6c8/mVHVdY5lnB8xXSCldzdoHG2VWQKfSwMpsRAhQLdFgtB2JjsVPzN+knG2bR4E5Hf0Qql3wLpUE0zssCFhbuwKAqF9m1PG0HPG0DWCowzTRrwkc6/1sHJw9kRl+ZpgyDxFVg62nRByLm7EF0TIO8Q82XAh1ek3xcJrJ+9GO/cjtEh6ZDvDVRlfINlEWi6PR9jyYn1RshORq18wW+0qqmiBOSYEZqPCmtSLUsgZyy18523QYLqEssBC+4+qMuNizaK69UbpvAUlQ9F+A9it46KlXVwN3r734rsz1L28VEg5hlgVd2UrVnmgqW9l/THy6bGDMVsaMmd7SMYUUXNa75jPWFP/s=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
